### ISSUE TITLE
Probable Bias in Algorithm Training Database

### ISSUE THREAD

**Issue by deadnameremoval** [mm909/Kaggle-Autism#6]
Hello,

I am autistic and just got curious about the model you have developed. As someone informed about the subject, I would like to share some possibly useful information.

First of all, bias in autism happens in several ways. The fact that this and most projects related to autism are directed towards children is a starting example of a kind of bias that happens: nobody develops anything for adults, where the diagnosis is much more complicated and is growing faster due to increased access to information. But that is not my only point here, as this tool is about children diagnosis.

I didn't look at the entire database, but I quickly sampled a systematic sample of 20 images (I must confess, I sampled systematically for convenience, not that there would be any benefit), taking 1 of every 50 pictures available. Of the 20 pictures, I have only found:

- 1 black kid. I know ethnical classifications vary from country to country, but in my country (Brazil) all other 19 kids would likely be classified as white. Black people are less likely to receive autism diagnosis.
- 3 girls. Girls are already a discriminated group in autism diagnosis less likely to get a diagnosis and often diagnosed later than boys, therefore the use of a database where girls are a minority tends to strength this gap in diagnosis.

On the non-autistic database, on the other hand, I did the same procedure and sample also 20 images, and while I didn't find any black kids there, I have found 6 girls in my sample, reinforcing that this bias is present in both samples.

Those biases are not exclusive from this project. Tools like, i.e., the Autistic Quotient and others used in professional diagnosis are known to be biased against non-whites and girls, too.

I hope my input is useful to improve your project. With a better database the project has the potential to help towards reducing those kinds of biases.

PS: If my sample does not correspond to the actual database,

Best regards,
Bruno Moreira-Guedes

**Comment by mm909** [comment]
Hey! 

Thanks for the feedback. I developed the project using an online data set available on Kaggle.com. I completely agree that the dataset has major issues. Anytime a researcher reaches out to me I recommend they do not take up the project until there is better data available. I voiced my concerns about the data quality to the original data publisher and I believe that the data set was, correctly, taken down. Although, I have not confirmed that is the case.

Thanks again for the response, hope all is well!
